# Generated by Django 5.0.7 on 2024-08-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siyyana_app', '0002_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name_plural': 'STATE'},
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siyyana_app.state')),
            ],
            options={
                'verbose_name_plural': 'DISTRICTS',
            },
        ),
    ]
