# Generated by Django 5.0.7 on 2024-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siyyana_app', '0003_alter_state_options_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SERVICES',
            },
        ),
    ]
