# Generated by Django 5.0.7 on 2024-08-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siyyana_app', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siyyana_app.services')),
            ],
            options={
                'verbose_name_plural': 'SUB SERVICES',
            },
        ),
    ]
