# Generated by Django 5.0.7 on 2024-08-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siyyana_app', '0005_subservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='SubServices',
            new_name='SubCategory',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'CATEGORY'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'SUBCATEGORY'},
        ),
    ]
